### ISSUE TITLE
Temperature in Fahrenheit? % after Humidity?

### ISSUE THREAD

**Issue by bleugray** [ajfriesen/ESPHome-AirGradient#7]
Is there a way to display the Temperature in Fahrenheit on the screen?  How would I add % after Humidity?

**Comment by ajfriesen** [comment]
There is an example in the docs:
https://esphome.io/components/sensor/index.html#example-converting-celsius-to-fahrenheit

Something like this but did not verify if that works:
```
sensor:
  - platform: sht3xd
    temperature:
      id: temp
      name: "Temperature"
    filters:
      - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"
```

**Comment by bleugray** [comment]
getting the error "filters is an invalid option for sensor.sht3xd"

**Comment by ajfriesen** [comment]
This is nothing specific to this project.

I would go and ask on the esphome discord or the home assistant forum.
You will find way more people knowing more about this than me 😉 
That is probably how you get an answer more likely and faster.
